### ISSUE TITLE
Adding Panorama files

### ISSUE THREAD

**Issue by PetervdPerk** [dotabuff/d2vpkr#4]
At the moment the Panorama UI files are missing.
These are css and xml files in the Dota/Panorama folder.
Can these be added ?

**Comment by watbe** [comment]
I suggest looking at the SteamDatabase/GameTracking-Dota2 repo for Panaroma files: https://github.com/SteamDatabase/GameTracking-Dota2/tree/master/game/dota/pak01_dir/panorama

Hope that's what you need!
